### ISSUE TITLE
error while using .dump(data)

### ISSUE THREAD

**Issue by osher** [connec/yaml-js#31]
I got the following error while trying to dump.
### Having:

```
C:\ws\nodejs\sandbox>node -v
v6.3.1

C:\ws\nodejs\sandbox>node
> require('yaml-js/package').version
'0.1.4'
```
### Scenario:

```
> require('yaml-js').dump({foo: 'bar'})
```
### Expected:

```
> require('yaml-js').dump({foo: 'bar'})
'foo: bar'
>
```
### Found:

```
> require('yaml-js').dump({foo: 'bar'})
tag is not specified
    at EmitterError.YAMLError [as constructor] (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\errors.js:70:46)
    at new EmitterError (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\emitter.js:17:49)
    at Resolver.__dirname.Emitter.Emitter.error (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\emitter.js:1298:13)
    at Resolver.__dirname.Emitter.Emitter.process_tag (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\emitter.js:619:14)
    at Resolver.__dirname.Emitter.Emitter.expect_node (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\emitter.js:282:14)
    at Resolver.__dirname.Emitter.Emitter.expect_document_root (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\emitter.js:265:19)
    at Resolver.__dirname.Emitter.Emitter.emit (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\emitter.js:116:14)
    at Resolver.__dirname.Serializer.Serializer.serialize_node (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\serializer.js:115:16)
    at Resolver.__dirname.Serializer.Serializer.serialize (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\serializer.js:64:14)
    at Resolver.__dirname.BaseRepresenter.BaseRepresenter.represent (C:\ws\nodejs\sandbox\node_modules\yaml-js\lib\representer.js:63:12)
>
```
## ..WTF?

help?

**Comment by connec** [comment]
Hrm. Seems to work fine in node 0.12 and 4.3. I'll fix this asap.

**Comment by osher** [comment]
roger that.

hmm. `6.5.0` works too.
