### ISSUE TITLE
Document with misindented/unescaped string causes "logic failure" error

### ISSUE THREAD

**Issue by kylef** [connec/yaml-js#46]
I didn't get a chance to fully dig into the underlying cause, just filing all the information to one place.

Given the following YAML document:

```yaml
openapi: 3.0.0
key:
  key:
      key: 'x
key: 'string'
```

The following error is emitted when using `yaml.compose()`:

```
Error: logic failure
    at Loader.Scanner.Scanner.save_possible_simple_key (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/scanner.js:302:15)
    at Loader.Scanner.Scanner.fetch_plain (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/scanner.js:566:12)
    at Loader.Scanner.Scanner.fetch_more_tokens (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/scanner.js:238:21)
    at Loader.Scanner.Scanner.check_token (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/scanner.js:115:14)
    at Loader.Parser.Parser.parse_block_mapping_key (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/parser.js:421:16)
    at Loader.Parser.Parser.check_event (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/parser.js:61:48)
    at Loader.Composer.Composer.compose_mapping_node (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/composer.js:248:20)
    at Loader.Composer.Composer.compose_node (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/composer.js:160:21)
    at Loader.Composer.Composer.compose_mapping_node (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/composer.js:250:27)
    at Loader.Composer.Composer.compose_node (/Users/kyle/Projects/apiaryio/api-elements.js/node_modules/yaml-js/lib/composer.js:160:21)
```

From https://github.com/connec/yaml-js/blob/fdfaa28/src/lib/scanner.coffee#L261

Expected:

An error with a message aimed at users explaining what they did wrong including a "context_mark" or "problem_mark".

Actual:

An internal error without source map information (marks)

**Comment by connec** [comment]
Thanks for the issue, but I'm going to close it since this repository is going to be archived. yaml-js has been unmaintained for some time, so it would be best to use something else.
